-- Categories and related words with short descriptors.
-- Assumes tables:
--   categories(id INTEGER PRIMARY KEY, name TEXT, description TEXT)
--   related_words(id INTEGER PRIMARY KEY, category_id INTEGER, category TEXT, word TEXT, description TEXT)
CREATE TABLE categories (
  id INTEGER PRIMARY KEY,
  name TEXT,
  description TEXT
);

CREATE TABLE related_words (
  id INTEGER PRIMARY KEY,
  category_id INTEGER,
  category TEXT,
  word TEXT,
  description TEXT
);


INSERT INTO categories (id, name, description) VALUES
(1, 'Cooking', 'Preparing food with heat, tools, and technique.'),
(2, 'Travel', 'Moving through places for work or leisure.'),
(3, 'Technology', 'Tools and systems that solve practical problems.'),
(4, 'Nature', 'Living ecosystems and the elements that shape them.'),
(5, 'Music', 'Organized sound used for expression and rhythm.'),
(6, 'Fitness', 'Training the body for strength, endurance, and health.'),
(7, 'Finance', 'Managing money, risk, and long-term goals.'),
(8, 'Education', 'Learning and teaching skills, facts, and ideas.'),
(9, 'Art', 'Creative work that communicates feeling or thought.'),
(10, 'Health', 'Well-being of body and mind in daily life.'),
(11, 'Business', 'Organizing people and resources to deliver value.'),
(12, 'Science', 'Systematic study of the natural world.'),
(13, 'Literature', 'Written works that explore story and meaning.'),
(14, 'Gardening', 'Cultivating plants for food, beauty, or habitat.'),
(15, 'Sports', 'Competitive games with rules, teams, and skill.'),
(16, 'Photography', 'Capturing moments with light, lens, and timing.'),
(17, 'Programming', 'Writing instructions that computers can execute.'),
(18, 'Cuisine', 'Regional styles of flavor, technique, and tradition.'),
(19, 'Movies', 'Visual stories told with actors, sound, and edits.'),
(20, 'Design', 'Planning form and function for clear user use.');

INSERT INTO related_words (id, category_id, category, word, description) VALUES
(1, 1, 'Cooking', 'simmer', 'Gentle heat that builds flavor without boiling.'),
(2, 1, 'Cooking', 'saute', 'Quick pan cooking that browns and lifts aroma.'),
(3, 1, 'Cooking', 'marinate', 'Soaking food to infuse herbs, acid, and spice.'),
(4, 1, 'Cooking', 'whisk', 'Rapid mixing to blend air and smooth texture.'),
(5, 1, 'Cooking', 'broil', 'High top heat that crisps surfaces fast.'),
(6, 1, 'Cooking', 'knead', 'Working dough to develop gluten and structure.'),
(7, 1, 'Cooking', 'reduce', 'Slowly thickening liquids to intensify taste.'),
(8, 1, 'Cooking', 'sear', 'Hot contact that seals surface and adds depth.'),
(9, 1, 'Cooking', 'zest', 'Citrus peel that brightens dishes with oils.'),
(10, 1, 'Cooking', 'blanch', 'Brief boil then chill to set color and bite.'),

(11, 2, 'Travel', 'itinerary', 'Planned route that organizes time and stops.'),
(12, 2, 'Travel', 'passport', 'Official ID needed for border entry and travel.'),
(13, 2, 'Travel', 'layover', 'Short stop between flights while in transit.'),
(14, 2, 'Travel', 'backpack', 'Portable storage for essentials on the move.'),
(15, 2, 'Travel', 'hostel', 'Budget lodging that favors shared spaces.'),
(16, 2, 'Travel', 'souvenir', 'Memento that ties a trip to a memory.'),
(17, 2, 'Travel', 'jetlag', 'Body clock shift after crossing time zones.'),
(18, 2, 'Travel', 'visa', 'Permission document for entry or extended stay.'),
(19, 2, 'Travel', 'guidebook', 'Reference that highlights culture, maps, and tips.'),
(20, 2, 'Travel', 'excursion', 'Short trip that adds a focused experience.'),

(21, 3, 'Technology', 'algorithm', 'Step-by-step logic that solves a defined task.'),
(22, 3, 'Technology', 'database', 'Structured storage for reliable data retrieval.'),
(23, 3, 'Technology', 'cloud', 'Remote computing resources delivered over network.'),
(24, 3, 'Technology', 'sensor', 'Device that detects change and reports signals.'),
(25, 3, 'Technology', 'encryption', 'Method that protects data through coded access.'),
(26, 3, 'Technology', 'bandwidth', 'Capacity that limits speed for data transfer.'),
(27, 3, 'Technology', 'interface', 'Connection layer between user and system actions.'),
(28, 3, 'Technology', 'firmware', 'Embedded software that controls device hardware.'),
(29, 3, 'Technology', 'automation', 'Processes that run with minimal human input.'),
(30, 3, 'Technology', 'latency', 'Delay between request and system response.'),

(31, 4, 'Nature', 'forest', 'Dense trees that shelter biodiversity and soil.'),
(32, 4, 'Nature', 'river', 'Flowing water that shapes land and habitat.'),
(33, 4, 'Nature', 'pollination', 'Transfer of pollen that enables plant reproduction.'),
(34, 4, 'Nature', 'climate', 'Long-term patterns of weather in a region.'),
(35, 4, 'Nature', 'habitat', 'Natural home that supports a species lifecycle.'),
(36, 4, 'Nature', 'wetland', 'Water-rich area that filters and buffers floods.'),
(37, 4, 'Nature', 'canopy', 'Upper layer of trees that controls light and rain.'),
(38, 4, 'Nature', 'erosion', 'Gradual wearing of land by wind or water.'),
(39, 4, 'Nature', 'biodiversity', 'Variety of life that strengthens ecosystems.'),
(40, 4, 'Nature', 'tundra', 'Cold plain with short growing seasons.'),

(41, 5, 'Music', 'melody', 'Singable line that carries the main theme; it guides emotion.'),
(42, 5, 'Music', 'rhythm', 'Pulse and pattern that drive timing and movement.'),
(43, 5, 'Music', 'harmony', 'Stacked tones that add color and tension.'),
(44, 5, 'Music', 'tempo', 'Speed of the beat that shapes energy.'),
(45, 5, 'Music', 'chorus', 'Repeated section that anchors the song.'),
(46, 5, 'Music', 'improv', 'Spontaneous playing that reacts to the moment.'),
(47, 5, 'Music', 'score', 'Written music that directs performance details.'),
(48, 5, 'Music', 'crescendo', 'Gradual rise in volume for dramatic lift.'),
(49, 5, 'Music', 'timbre', 'Tone quality that distinguishes instruments or voices.'),
(50, 5, 'Music', 'beat', 'Regular accent that listeners can follow.'),

(51, 6, 'Fitness', 'cardio', 'Heart-rate training that boosts endurance.'),
(52, 6, 'Fitness', 'strength', 'Resistance work that builds muscle and power.'),
(53, 6, 'Fitness', 'mobility', 'Range of motion that keeps joints healthy.'),
(54, 6, 'Fitness', 'intervals', 'Alternating effort and rest for performance gains.'),
(55, 6, 'Fitness', 'stretch', 'Lengthening muscles to reduce tightness.'),
(56, 6, 'Fitness', 'core', 'Midsection stability that supports posture and balance.'),
(57, 6, 'Fitness', 'reps', 'Repeated movements that build volume and skill.'),
(58, 6, 'Fitness', 'endurance', 'Ability to sustain effort over time.'),
(59, 6, 'Fitness', 'recovery', 'Rest process that rebuilds tissue and energy.'),
(60, 6, 'Fitness', 'form', 'Technique that keeps movement safe and efficient.'),

(61, 7, 'Finance', 'budget', 'Plan that assigns money to goals and needs.'),
(62, 7, 'Finance', 'savings', 'Funds set aside for future use.'),
(63, 7, 'Finance', 'investment', 'Capital placed to grow over time.'),
(64, 7, 'Finance', 'interest', 'Cost or gain of borrowing money.'),
(65, 7, 'Finance', 'credit', 'Borrowing capacity based on trust and history.'),
(66, 7, 'Finance', 'debt', 'Money owed that must be repaid.'),
(67, 7, 'Finance', 'dividend', 'Share of profits paid to investors.'),
(68, 7, 'Finance', 'inflation', 'Rising prices that reduce buying power.'),
(69, 7, 'Finance', 'liquidity', 'Ease of turning assets into cash.'),
(70, 7, 'Finance', 'portfolio', 'Collection of holdings balanced by risk.'),

(71, 8, 'Education', 'curriculum', 'Planned set of lessons and outcomes.'),
(72, 8, 'Education', 'lecture', 'Instructor-led talk that conveys concepts.'),
(73, 8, 'Education', 'assignment', 'Task that reinforces skill practice.'),
(74, 8, 'Education', 'assessment', 'Measurement of learning and progress.'),
(75, 8, 'Education', 'mentorship', 'Guidance relationship that supports growth.'),
(76, 8, 'Education', 'literacy', 'Ability to read, write, and comprehend.'),
(77, 8, 'Education', 'syllabus', 'Outline that sets scope and expectations.'),
(78, 8, 'Education', 'workshop', 'Hands-on session for applied learning.'),
(79, 8, 'Education', 'feedback', 'Response that helps improve performance.'),
(80, 8, 'Education', 'research', 'Inquiry that builds knowledge or evidence.'),

(81, 9, 'Art', 'canvas', 'Surface that receives paint or mixed media.'),
(82, 9, 'Art', 'palette', 'Selection of colors used in a piece.'),
(83, 9, 'Art', 'composition', 'Arrangement that guides the viewer''s eye.'),
(84, 9, 'Art', 'contrast', 'Difference in value that creates emphasis.'),
(85, 9, 'Art', 'texture', 'Visual or tactile surface quality.'),
(86, 9, 'Art', 'sketch', 'Quick study that explores shape and idea.'),
(87, 9, 'Art', 'perspective', 'Technique that shows depth and scale.'),
(88, 9, 'Art', 'medium', 'Material or method used to create work.'),
(89, 9, 'Art', 'motif', 'Recurring element that builds cohesion.'),
(90, 9, 'Art', 'critique', 'Structured review that refines the work.'),

(91, 10, 'Health', 'nutrition', 'Food quality that fuels and repairs the body.'),
(92, 10, 'Health', 'hydration', 'Water balance that keeps systems running.'),
(93, 10, 'Health', 'sleep', 'Rest cycle that supports recovery and focus.'),
(94, 10, 'Health', 'immunity', 'Defense system that resists illness.'),
(95, 10, 'Health', 'mindfulness', 'Attention practice that reduces stress.'),
(96, 10, 'Health', 'checkup', 'Routine visit that monitors overall health.'),
(97, 10, 'Health', 'symptom', 'Signal that indicates a body issue.'),
(98, 10, 'Health', 'therapy', 'Treatment plan for mental or physical care.'),
(99, 10, 'Health', 'balance', 'Healthy mix of work, rest, and play.'),
(100, 10, 'Health', 'prevention', 'Habits that reduce future health risks.'),

(101, 11, 'Business', 'strategy', 'Plan that aligns goals with competitive moves.'),
(102, 11, 'Business', 'stakeholder', 'Person affected by or invested in outcomes.'),
(103, 11, 'Business', 'revenue', 'Income earned from products or services.'),
(104, 11, 'Business', 'operations', 'Daily processes that keep a business running.'),
(105, 11, 'Business', 'leadership', 'Guiding people toward shared objectives.'),
(106, 11, 'Business', 'market', 'Group of buyers with similar needs.'),
(107, 11, 'Business', 'branding', 'Identity that shapes customer perception.'),
(108, 11, 'Business', 'scaling', 'Growth process that preserves efficiency.'),
(109, 11, 'Business', 'proposal', 'Formal offer that defines scope and terms.'),
(110, 11, 'Business', 'customer', 'Person who uses and pays for value.'),

(111, 12, 'Science', 'hypothesis', 'Testable idea that frames a scientific question.'),
(112, 12, 'Science', 'experiment', 'Controlled test that gathers evidence.'),
(113, 12, 'Science', 'data', 'Measured observations used to analyze results.'),
(114, 12, 'Science', 'theory', 'Well-supported explanation for natural behavior.'),
(115, 12, 'Science', 'variable', 'Factor that can change in a study.'),
(116, 12, 'Science', 'analysis', 'Interpretation that reveals patterns in results.'),
(117, 12, 'Science', 'peerreview', 'Expert critique that checks methods and claims.'),
(118, 12, 'Science', 'lab', 'Workspace for observation and testing.'),
(119, 12, 'Science', 'model', 'Simplified representation of complex systems.'),
(120, 12, 'Science', 'evidence', 'Proof that supports or refutes a claim.'),

(121, 13, 'Literature', 'narrative', 'Story structure that carries events and meaning.'),
(122, 13, 'Literature', 'character', 'Person in a story who drives action.'),
(123, 13, 'Literature', 'theme', 'Core idea that unifies the work.'),
(124, 13, 'Literature', 'metaphor', 'Comparison that adds depth to interpretation.'),
(125, 13, 'Literature', 'prose', 'Ordinary writing style without line breaks.'),
(126, 13, 'Literature', 'poetry', 'Condensed language focused on rhythm and image.'),
(127, 13, 'Literature', 'genre', 'Category that signals style and expectations.'),
(128, 13, 'Literature', 'plot', 'Sequence of events that builds tension.'),
(129, 13, 'Literature', 'dialogue', 'Spoken exchange that reveals character.'),
(130, 13, 'Literature', 'setting', 'Time and place that ground the story.'),

(131, 14, 'Gardening', 'compost', 'Decomposed matter that enriches soil health.'),
(132, 14, 'Gardening', 'mulch', 'Covering that retains moisture and blocks weeds.'),
(133, 14, 'Gardening', 'pruning', 'Cutting back plants to guide growth.'),
(134, 14, 'Gardening', 'seedling', 'Young plant started from seed.'),
(135, 14, 'Gardening', 'irrigation', 'Planned watering that supports steady growth.'),
(136, 14, 'Gardening', 'perennial', 'Plant that returns year after year.'),
(137, 14, 'Gardening', 'fertilizer', 'Nutrients added to improve plant vigor.'),
(138, 14, 'Gardening', 'bed', 'Prepared plot where plants are grown.'),
(139, 14, 'Gardening', 'pollinator', 'Insect or bird that moves pollen between blooms.'),
(140, 14, 'Gardening', 'transplant', 'Move a plant to a new location.'),

(141, 15, 'Sports', 'tournament', 'Bracketed event that ranks teams or players.'),
(142, 15, 'Sports', 'referee', 'Official who enforces rules and fairness.'),
(143, 15, 'Sports', 'training', 'Practice routine that builds skill and stamina.'),
(144, 15, 'Sports', 'season', 'Scheduled period of organized competition.'),
(145, 15, 'Sports', 'scoreboard', 'Display that tracks points and time.'),
(146, 15, 'Sports', 'playoff', 'Elimination rounds that decide a champion.'),
(147, 15, 'Sports', 'teamwork', 'Coordinated effort toward a shared win.'),
(148, 15, 'Sports', 'draft', 'Selection process for building a roster.'),
(149, 15, 'Sports', 'stadium', 'Venue built for spectators and athletes.'),
(150, 15, 'Sports', 'athlete', 'Competitor who trains for performance.'),

(151, 16, 'Photography', 'exposure', 'Light control that shapes brightness and detail.'),
(152, 16, 'Photography', 'aperture', 'Lens opening that sets depth of field.'),
(153, 16, 'Photography', 'shutter', 'Timing control that freezes or blurs motion.'),
(154, 16, 'Photography', 'focus', 'Sharpness point that directs viewer attention.'),
(155, 16, 'Photography', 'composition', 'Framing choices that balance the scene.'),
(156, 16, 'Photography', 'portrait', 'Image focused on a person and expression.'),
(157, 16, 'Photography', 'landscape', 'Wide scene that highlights environment.'),
(158, 16, 'Photography', 'contrast', 'Difference in tones that adds dimension.'),
(159, 16, 'Photography', 'lens', 'Optics that determine field of view.'),
(160, 16, 'Photography', 'edit', 'Post-processing that refines color and clarity.'),

(161, 17, 'Programming', 'syntax', 'Rules that define valid code structure.'),
(162, 17, 'Programming', 'compile', 'Transforming source into runnable output.'),
(163, 17, 'Programming', 'debug', 'Finding and fixing code defects.'),
(164, 17, 'Programming', 'runtime', 'Execution environment for a program.'),
(165, 17, 'Programming', 'library', 'Reusable code that adds capabilities.'),
(166, 17, 'Programming', 'function', 'Named block that performs a task.'),
(167, 17, 'Programming', 'variable', 'Named storage for changing values.'),
(168, 17, 'Programming', 'loop', 'Repeated execution over a sequence.'),
(169, 17, 'Programming', 'exception', 'Error event that interrupts normal flow.'),
(170, 17, 'Programming', 'version', 'Tracked state of code over time.'),

(171, 18, 'Cuisine', 'spice', 'Seasoning blend that defines regional heat.'),
(172, 18, 'Cuisine', 'stew', 'Slow-cooked dish that melds flavors.'),
(173, 18, 'Cuisine', 'streetfood', 'Portable bites tied to local culture.'),
(174, 18, 'Cuisine', 'herb', 'Fresh leaf flavor that lifts a dish.'),
(175, 18, 'Cuisine', 'broth', 'Savory liquid base for soups and sauces.'),
(176, 18, 'Cuisine', 'ferment', 'Process that deepens flavor and preserves.'),
(177, 18, 'Cuisine', 'noodle', 'Staple starch shaped for sauces or soups.'),
(178, 18, 'Cuisine', 'grill', 'Open heat method for char and smoke.'),
(179, 18, 'Cuisine', 'sauce', 'Complement that ties ingredients together.'),
(180, 18, 'Cuisine', 'dessert', 'Sweet finish that reflects local tradition.'),

(181, 19, 'Movies', 'screenplay', 'Script that defines dialogue, action, and pacing.'),
(182, 19, 'Movies', 'director', 'Lead creative who shapes the final film.'),
(183, 19, 'Movies', 'cinematography', 'Visual style built by camera and light.'),
(184, 19, 'Movies', 'montage', 'Edited sequence that compresses time.'),
(185, 19, 'Movies', 'soundtrack', 'Music that supports mood and narrative.'),
(186, 19, 'Movies', 'premiere', 'First public showing of a film.'),
(187, 19, 'Movies', 'genre', 'Category that signals tone and audience.'),
(188, 19, 'Movies', 'trailer', 'Short preview that highlights key moments.'),
(189, 19, 'Movies', 'scene', 'Contained segment that advances the story.'),
(190, 19, 'Movies', 'credits', 'List of people who made the film.'),

(191, 20, 'Design', 'layout', 'Placement of elements to guide user flow.'),
(192, 20, 'Design', 'typography', 'Type choices that set tone and clarity.'),
(193, 20, 'Design', 'grid', 'Structure that aligns and balances content.'),
(194, 20, 'Design', 'contrast', 'Visual difference that creates emphasis.'),
(195, 20, 'Design', 'prototype', 'Working draft that tests an idea quickly.'),
(196, 20, 'Design', 'icon', 'Symbol that conveys function at a glance.'),
(197, 20, 'Design', 'whitespace', 'Empty space that improves focus and readability.'),
(198, 20, 'Design', 'affordance', 'Visual cue that suggests how to interact.'),
(199, 20, 'Design', 'usability', 'Ease of use based on user needs.'),
(200, 20, 'Design', 'hierarchy', 'Order of importance that guides attention.');
