export const cooking = [
  {"title" : "Saute" , "definition" : "To cook food quickly in a small amount of hot oil or fat over high heat."},
  {"title" : "Simmer" , "definition" : "To cook food gently in liquid at a temperature just below boiling point."},
  {"title" : "Roast" , "definition" : "To cook food, especially meat, by dry heat in an oven or over an open fire."},
  {"title" : "Blanch" , "definition" : "To briefly cook food in boiling water and then transfer it to cold water to stop the cooking process."},
  {"title" : "Braise" , "definition" : "To cook food slowly in a closed pot with a small amount of liquid, typically resulting in tender and flavorful dishes."},
  {"title" : "Grate" , "definition" : "To shred food into small pieces using a grater."},
  {"title" : "Marinate" , "definition" : "To soak food in a seasoned liquid mixture to enhance flavor and tenderness."},
  {"title" : "Sear" , "definition" : "To quickly cook the surface of food at high heat to seal in juices and create a browned crust."},
  {"title" : "Whip" , "definition" : "To beat ingredients vigorously to incorporate air and increase volume, typically done with cream or egg whites."},
  {"title" : "Mince" , "definition" : "To finely chop food into very small pieces."},
  {"title" : "Deglaze" , "definition" : "To add liquid, such as wine or broth, to a pan to dissolve and incorporate the flavorful browned bits left after cooking."},
  {"title" : "Knead" , "definition" : "To work dough with hands to develop gluten and create a smooth and elastic texture."},
  {"title" : "Zest" , "definition" : "To grate or peel the outer colored part of citrus fruits, used to add flavor to dishes."},
  {"title" : "Fold" , "definition" : "To gently combine ingredients by using a spatula or spoon in a lifting and turning motion to maintain airiness."},
  {"title" : "Steam" , "definition" : "To cook food by exposing it to steam, typically done using a steamer or a covered pot with a small amount of water."},
  {"title" : "Season" , "definition" : "To add salt, herbs, spices, or other flavorings to enhance the taste of food."},
  {"title" : "Caramelize" , "definition" : "To heat sugar until it melts and turns into a golden-brown syrup, adding a rich flavor to dishes."},
  {"title" : "Reduce" , "definition" : "To simmer a liquid to evaporate some of the water content, resulting in a thicker and more concentrated sauce or broth."},
  {"title" : "Broil" , "definition" : "To cook food by exposing it to direct heat from above, typically done in an oven or under a grill."},
  {"title" : "Garnish" , "definition" : "To decorate or embellish a dish with additional ingredients, such as herbs, sauces, or edible flowers, for visual appeal."},
];
